/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KunderIndexRouteImport } from './routes/kunder.index'
import { Route as FakturorIndexRouteImport } from './routes/fakturor.index'
import { Route as BehandlingarIndexRouteImport } from './routes/behandlingar.index'
import { Route as KunderNyRouteImport } from './routes/kunder.ny'
import { Route as KunderIdRouteImport } from './routes/kunder.$id'
import { Route as HastarNyRouteImport } from './routes/hastar.ny'
import { Route as HastarIdRouteImport } from './routes/hastar.$id'
import { Route as FakturorNyRouteImport } from './routes/fakturor.ny'
import { Route as FakturorIdRouteImport } from './routes/fakturor.$id'
import { Route as BehandlingarNyRouteImport } from './routes/behandlingar.ny'
import { Route as ApiPhotosSplatRouteImport } from './routes/api.photos.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KunderIndexRoute = KunderIndexRouteImport.update({
  id: '/kunder/',
  path: '/kunder/',
  getParentRoute: () => rootRouteImport,
} as any)
const FakturorIndexRoute = FakturorIndexRouteImport.update({
  id: '/fakturor/',
  path: '/fakturor/',
  getParentRoute: () => rootRouteImport,
} as any)
const BehandlingarIndexRoute = BehandlingarIndexRouteImport.update({
  id: '/behandlingar/',
  path: '/behandlingar/',
  getParentRoute: () => rootRouteImport,
} as any)
const KunderNyRoute = KunderNyRouteImport.update({
  id: '/kunder/ny',
  path: '/kunder/ny',
  getParentRoute: () => rootRouteImport,
} as any)
const KunderIdRoute = KunderIdRouteImport.update({
  id: '/kunder/$id',
  path: '/kunder/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const HastarNyRoute = HastarNyRouteImport.update({
  id: '/hastar/ny',
  path: '/hastar/ny',
  getParentRoute: () => rootRouteImport,
} as any)
const HastarIdRoute = HastarIdRouteImport.update({
  id: '/hastar/$id',
  path: '/hastar/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const FakturorNyRoute = FakturorNyRouteImport.update({
  id: '/fakturor/ny',
  path: '/fakturor/ny',
  getParentRoute: () => rootRouteImport,
} as any)
const FakturorIdRoute = FakturorIdRouteImport.update({
  id: '/fakturor/$id',
  path: '/fakturor/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BehandlingarNyRoute = BehandlingarNyRouteImport.update({
  id: '/behandlingar/ny',
  path: '/behandlingar/ny',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPhotosSplatRoute = ApiPhotosSplatRouteImport.update({
  id: '/api/photos/$',
  path: '/api/photos/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/behandlingar/ny': typeof BehandlingarNyRoute
  '/fakturor/$id': typeof FakturorIdRoute
  '/fakturor/ny': typeof FakturorNyRoute
  '/hastar/$id': typeof HastarIdRoute
  '/hastar/ny': typeof HastarNyRoute
  '/kunder/$id': typeof KunderIdRoute
  '/kunder/ny': typeof KunderNyRoute
  '/behandlingar/': typeof BehandlingarIndexRoute
  '/fakturor/': typeof FakturorIndexRoute
  '/kunder/': typeof KunderIndexRoute
  '/api/photos/$': typeof ApiPhotosSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/behandlingar/ny': typeof BehandlingarNyRoute
  '/fakturor/$id': typeof FakturorIdRoute
  '/fakturor/ny': typeof FakturorNyRoute
  '/hastar/$id': typeof HastarIdRoute
  '/hastar/ny': typeof HastarNyRoute
  '/kunder/$id': typeof KunderIdRoute
  '/kunder/ny': typeof KunderNyRoute
  '/behandlingar': typeof BehandlingarIndexRoute
  '/fakturor': typeof FakturorIndexRoute
  '/kunder': typeof KunderIndexRoute
  '/api/photos/$': typeof ApiPhotosSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/behandlingar/ny': typeof BehandlingarNyRoute
  '/fakturor/$id': typeof FakturorIdRoute
  '/fakturor/ny': typeof FakturorNyRoute
  '/hastar/$id': typeof HastarIdRoute
  '/hastar/ny': typeof HastarNyRoute
  '/kunder/$id': typeof KunderIdRoute
  '/kunder/ny': typeof KunderNyRoute
  '/behandlingar/': typeof BehandlingarIndexRoute
  '/fakturor/': typeof FakturorIndexRoute
  '/kunder/': typeof KunderIndexRoute
  '/api/photos/$': typeof ApiPhotosSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/behandlingar/ny'
    | '/fakturor/$id'
    | '/fakturor/ny'
    | '/hastar/$id'
    | '/hastar/ny'
    | '/kunder/$id'
    | '/kunder/ny'
    | '/behandlingar/'
    | '/fakturor/'
    | '/kunder/'
    | '/api/photos/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/behandlingar/ny'
    | '/fakturor/$id'
    | '/fakturor/ny'
    | '/hastar/$id'
    | '/hastar/ny'
    | '/kunder/$id'
    | '/kunder/ny'
    | '/behandlingar'
    | '/fakturor'
    | '/kunder'
    | '/api/photos/$'
  id:
    | '__root__'
    | '/'
    | '/behandlingar/ny'
    | '/fakturor/$id'
    | '/fakturor/ny'
    | '/hastar/$id'
    | '/hastar/ny'
    | '/kunder/$id'
    | '/kunder/ny'
    | '/behandlingar/'
    | '/fakturor/'
    | '/kunder/'
    | '/api/photos/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BehandlingarNyRoute: typeof BehandlingarNyRoute
  FakturorIdRoute: typeof FakturorIdRoute
  FakturorNyRoute: typeof FakturorNyRoute
  HastarIdRoute: typeof HastarIdRoute
  HastarNyRoute: typeof HastarNyRoute
  KunderIdRoute: typeof KunderIdRoute
  KunderNyRoute: typeof KunderNyRoute
  BehandlingarIndexRoute: typeof BehandlingarIndexRoute
  FakturorIndexRoute: typeof FakturorIndexRoute
  KunderIndexRoute: typeof KunderIndexRoute
  ApiPhotosSplatRoute: typeof ApiPhotosSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kunder/': {
      id: '/kunder/'
      path: '/kunder'
      fullPath: '/kunder/'
      preLoaderRoute: typeof KunderIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fakturor/': {
      id: '/fakturor/'
      path: '/fakturor'
      fullPath: '/fakturor/'
      preLoaderRoute: typeof FakturorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/behandlingar/': {
      id: '/behandlingar/'
      path: '/behandlingar'
      fullPath: '/behandlingar/'
      preLoaderRoute: typeof BehandlingarIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kunder/ny': {
      id: '/kunder/ny'
      path: '/kunder/ny'
      fullPath: '/kunder/ny'
      preLoaderRoute: typeof KunderNyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kunder/$id': {
      id: '/kunder/$id'
      path: '/kunder/$id'
      fullPath: '/kunder/$id'
      preLoaderRoute: typeof KunderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hastar/ny': {
      id: '/hastar/ny'
      path: '/hastar/ny'
      fullPath: '/hastar/ny'
      preLoaderRoute: typeof HastarNyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hastar/$id': {
      id: '/hastar/$id'
      path: '/hastar/$id'
      fullPath: '/hastar/$id'
      preLoaderRoute: typeof HastarIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fakturor/ny': {
      id: '/fakturor/ny'
      path: '/fakturor/ny'
      fullPath: '/fakturor/ny'
      preLoaderRoute: typeof FakturorNyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fakturor/$id': {
      id: '/fakturor/$id'
      path: '/fakturor/$id'
      fullPath: '/fakturor/$id'
      preLoaderRoute: typeof FakturorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/behandlingar/ny': {
      id: '/behandlingar/ny'
      path: '/behandlingar/ny'
      fullPath: '/behandlingar/ny'
      preLoaderRoute: typeof BehandlingarNyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/photos/$': {
      id: '/api/photos/$'
      path: '/api/photos/$'
      fullPath: '/api/photos/$'
      preLoaderRoute: typeof ApiPhotosSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BehandlingarNyRoute: BehandlingarNyRoute,
  FakturorIdRoute: FakturorIdRoute,
  FakturorNyRoute: FakturorNyRoute,
  HastarIdRoute: HastarIdRoute,
  HastarNyRoute: HastarNyRoute,
  KunderIdRoute: KunderIdRoute,
  KunderNyRoute: KunderNyRoute,
  BehandlingarIndexRoute: BehandlingarIndexRoute,
  FakturorIndexRoute: FakturorIndexRoute,
  KunderIndexRoute: KunderIndexRoute,
  ApiPhotosSplatRoute: ApiPhotosSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
